package main

import (
	"time"

	"yazilimgrubu.com/prettifer/entities"
)

func main() {

	prettifer := entities.CreateNew()
	var credentials []interface{} = make([]interface{}, 2)
	credentials[0] = Credential{URLAddress: "127.0.0.1", Port: 5432, UserName: "admin", Password: "123456+a", CreateDate: time.Date(2021, 1, 1, 0, 0, 0, 0, time.UTC), SSL: SSL{SSL: "disable", Mode: "SSL"}}
	credentials[1] = Credential{URLAddress: "127.0.0.1", Port: 5432, UserName: "root", Password: "123456+a", CreateDate: time.Now(), SSL: SSL{SSL: "disable", Mode: "SSL"}}
	prettifer.Settings.Columns = []*entities.Column{
		{
			IsAutoGenerated: false,
			Name:            "CreateDate",
			Header:          "Create Date",
			Align:           entities.AL_LEFT,
			Order:           5,
			MinWidth:        20,
			MaxWidth:        25,
		},
		{
			IsAutoGenerated: false,
			Name:            "SSL",
			Header:          "Status",
			Align:           entities.AL_LEFT,
			Order:           5,
			MinWidth:        20,
			MaxWidth:        30,
			CalculateFunc: func(v interface{}, i int) string {
				t := v.(SSL)
				return t.Mode + " " + t.SSL
			},
		},
	}
	prettifer.AddExcludedField("SSL")
	prettifer.ToStdOutput(credentials...)
}

type Credential struct {
	URLAddress string
	Port       int
	UserName   string
	Password   string
	CreateDate time.Time
	SSL        SSL
}

type SSL struct {
	SSL  string
	Mode string
}
