package main

import (
	"time"

	"yazilimgrubu.com/prettifer/entities"
)

func main() {

	prettifer := entities.CreateNew()
	var tests []interface{} = make([]interface{}, 2)
	tests[0] = test{URLAddress: "127.0.0.1", Port: 5432, UserName: "olcayguzel", Password: "123456+a", CreateDate: time.Now(), T1: t1{SSL: "false", Mode: "dsf"}}
	tests[1] = test{URLAddress: "127.0.0.1", Port: 5432, UserName: "root", Password: "123456+a", CreateDate: time.Now(), T1: t1{SSL: "false", Mode: "abc"}}
	prettifer.Settings.Columns = []*entities.Column{
		{
			IsAutoGenerated: false,
			Name:            "CreateDate",
			Header:          "Create Date",
			Align:           entities.AL_LEFT,
			Order:           5,
			MinWidth:        20,
			MaxWidth:        30,
		},
		{
			IsAutoGenerated: false,
			Name:            "T1",
			Header:          "Test Field",
			Align:           entities.AL_LEFT,
			Order:           5,
			MinWidth:        20,
			MaxWidth:        30,
			CalculateFunc: func(i interface{}) string {
				t := i.(t1)
				return t.Mode + " " + t.SSL
			},
		},
	}
	prettifer.AddExcludedField("T1")
	prettifer.ToStdOutput(tests...)
}

type test struct {
	URLAddress string
	Port       int
	UserName   string
	Password   string
	CreateDate time.Time
	T1         t1
}

type t1 struct {
	SSL  string
	Mode string
}
