package entities

type Column struct {
	IsAutoGenerated bool
	Name            string
	Header          string
	Align           Alignment
	Format          string
	Order           int
	MaxWidth        int
	MinWidth        int
	Width           int
	Type            DataType
	CalculateFunc   func(interface{}, int) string
}
